name = "server-sg" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
node_compat = true
workers_dev = true
[[route]]
pattern = "runako.my.id"
custom_domain = true
[[route]]
pattern = "ava.game.naver.com.runako.my.id"
custom_domain = true
[[route]]
pattern = "graph.instagram.com.runako.my.id"
custom_domain = true
[[route]]
pattern = "cache.netflix.com.runako.my.id"
custom_domain = true
[[route]]
pattern = "zaintest.vuclip.com.runako.my.id"
custom_domain = true
[[route]]
pattern = "access.iflix.com.runako.my.id"
custom_domain = true
[[route]]
pattern = "investors.spotify.com.runako.my.id"
custom_domain = true
[[route]]
pattern = "support.zoom.us.runako.my.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "59274f05-1440-4ab0-9edf-d5986e1836b5"
